/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'shopItem' : ShopItem, 'quantity' : bigint }
export interface OrderDetails {
  'status' : PurchaseStatus,
  'identityName' : string,
  'minecraftUsername' : string,
  'totalAmount' : bigint,
  'timestamp' : bigint,
  'purchaser' : Principal,
  'discordUsername' : string,
  'items' : Array<CartItem>,
}
export interface PurchaseRecord {
  'status' : PurchaseStatus,
  'minecraftUsername' : string,
  'totalAmount' : bigint,
  'timestamp' : bigint,
  'discordUsername' : string,
  'items' : Array<CartItem>,
}
export type PurchaseStatus = { 'unapproved' : null } |
  { 'approved' : null };
export interface ShopItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : string,
  'price' : bigint,
}
export interface UPIConfig { 'merchantName' : string, 'upiId' : string }
export interface UserProfile { 'name' : string, 'minecraftUsername' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WebsiteConfig {
  'homeTagline' : string,
  'serverMemberCount' : bigint,
  'discordInviteLink' : string,
  'serverOnlineStatus' : boolean,
  'votePageUrls' : Array<string>,
  'serverIp' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addShopItem' : ActorMethod<
    [string, string, bigint, string, boolean],
    bigint
  >,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'approveOrder' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'completePurchaseWithUPI' : ActorMethod<[string, string], undefined>,
  'deleteShopItem' : ActorMethod<[bigint], undefined>,
  'editShopItem' : ActorMethod<
    [bigint, string, string, bigint, string, boolean],
    undefined
  >,
  'getAllOrders' : ActorMethod<[], Array<OrderDetails>>,
  'getAllShopItems' : ActorMethod<[], Array<ShopItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getPurchaseHistory' : ActorMethod<[], Array<PurchaseRecord>>,
  'getShopItemsByCategory' : ActorMethod<[string], Array<ShopItem>>,
  'getUPIConfig' : ActorMethod<[], UPIConfig>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWebsiteConfig' : ActorMethod<[], WebsiteConfig>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerWithMinecraftUsername' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateUPIConfig' : ActorMethod<[string, string], undefined>,
  'updateUserMinecraftUsername' : ActorMethod<[Principal, string], undefined>,
  'updateWebsiteConfig' : ActorMethod<
    [string, Array<string>, string, string, boolean, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];