/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PurchaseStatus = IDL.Variant({
  'unapproved' : IDL.Null,
  'approved' : IDL.Null,
});
export const ShopItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'shopItem' : ShopItem,
  'quantity' : IDL.Nat,
});
export const OrderDetails = IDL.Record({
  'status' : PurchaseStatus,
  'identityName' : IDL.Text,
  'minecraftUsername' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'purchaser' : IDL.Principal,
  'discordUsername' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'minecraftUsername' : IDL.Text,
});
export const PurchaseRecord = IDL.Record({
  'status' : PurchaseStatus,
  'minecraftUsername' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'discordUsername' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const UPIConfig = IDL.Record({
  'merchantName' : IDL.Text,
  'upiId' : IDL.Text,
});
export const WebsiteConfig = IDL.Record({
  'homeTagline' : IDL.Text,
  'serverMemberCount' : IDL.Nat,
  'discordInviteLink' : IDL.Text,
  'serverOnlineStatus' : IDL.Bool,
  'votePageUrls' : IDL.Vec(IDL.Text),
  'serverIp' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addShopItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'approveOrder' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'completePurchaseWithUPI' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteShopItem' : IDL.Func([IDL.Nat], [], []),
  'editShopItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderDetails)], ['query']),
  'getAllShopItems' : IDL.Func([], [IDL.Vec(ShopItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getPurchaseHistory' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
  'getShopItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ShopItem)],
      ['query'],
    ),
  'getUPIConfig' : IDL.Func([], [UPIConfig], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWebsiteConfig' : IDL.Func([], [WebsiteConfig], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerWithMinecraftUsername' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateUPIConfig' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateUserMinecraftUsername' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateWebsiteConfig' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PurchaseStatus = IDL.Variant({
    'unapproved' : IDL.Null,
    'approved' : IDL.Null,
  });
  const ShopItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'shopItem' : ShopItem, 'quantity' : IDL.Nat });
  const OrderDetails = IDL.Record({
    'status' : PurchaseStatus,
    'identityName' : IDL.Text,
    'minecraftUsername' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'purchaser' : IDL.Principal,
    'discordUsername' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'minecraftUsername' : IDL.Text,
  });
  const PurchaseRecord = IDL.Record({
    'status' : PurchaseStatus,
    'minecraftUsername' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'discordUsername' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const UPIConfig = IDL.Record({
    'merchantName' : IDL.Text,
    'upiId' : IDL.Text,
  });
  const WebsiteConfig = IDL.Record({
    'homeTagline' : IDL.Text,
    'serverMemberCount' : IDL.Nat,
    'discordInviteLink' : IDL.Text,
    'serverOnlineStatus' : IDL.Bool,
    'votePageUrls' : IDL.Vec(IDL.Text),
    'serverIp' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addShopItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'approveOrder' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'completePurchaseWithUPI' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteShopItem' : IDL.Func([IDL.Nat], [], []),
    'editShopItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderDetails)], ['query']),
    'getAllShopItems' : IDL.Func([], [IDL.Vec(ShopItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getPurchaseHistory' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
    'getShopItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ShopItem)],
        ['query'],
      ),
    'getUPIConfig' : IDL.Func([], [UPIConfig], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWebsiteConfig' : IDL.Func([], [WebsiteConfig], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerWithMinecraftUsername' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateUPIConfig' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateUserMinecraftUsername' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateWebsiteConfig' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };