/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type BackgroundSetting = {
    __kind__: "color";
    color: {
        value: string;
    };
} | {
    __kind__: "image";
    image: {
        value: string;
    };
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface UPIConfig {
    merchantName: string;
    upiId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ShopItem {
    id: bigint;
    name: string;
    description: string;
    available: boolean;
    category: string;
    price: bigint;
}
export type Logo = {
    __kind__: "url";
    url: string;
} | {
    __kind__: "blob";
    blob: ExternalBlob;
};
export interface PurchaseRecord {
    status: PurchaseStatus;
    minecraftUsername: string;
    totalAmount: bigint;
    timestamp: bigint;
    discordUsername: string;
    items: Array<CartItem>;
}
export interface OrderDetails {
    status: PurchaseStatus;
    identityName: string;
    minecraftUsername: string;
    totalAmount: bigint;
    timestamp: bigint;
    purchaser: Principal;
    discordUsername: string;
    items: Array<CartItem>;
}
export interface CartItem {
    shopItem: ShopItem;
    quantity: bigint;
}
export interface WebsiteConfig {
    homeTagline: string;
    logo: Logo;
    serverMemberCount: bigint;
    discordInviteLink: string;
    backgroundSetting: BackgroundSetting;
    serverOnlineStatus: boolean;
    votePageUrls: Array<string>;
    serverIp: string;
}
export interface UserProfile {
    name: string;
    minecraftUsername: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum PurchaseStatus {
    unapproved = "unapproved",
    approved = "approved"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addShopItem(name: string, description: string, price: bigint, category: string, available: boolean): Promise<bigint>;
    addToCart(itemId: bigint, quantity: bigint): Promise<void>;
    approveOrder(user: Principal, orderId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCart(): Promise<void>;
    completePurchaseWithUPI(minecraftUsername: string, discordUsername: string): Promise<void>;
    deleteShopItem(id: bigint): Promise<void>;
    editShopItem(id: bigint, name: string, description: string, price: bigint, category: string, available: boolean): Promise<void>;
    getAllOrders(): Promise<Array<OrderDetails>>;
    getAllShopItems(): Promise<Array<ShopItem>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<Array<CartItem>>;
    getPurchaseHistory(): Promise<Array<PurchaseRecord>>;
    getShopItemsByCategory(category: string): Promise<Array<ShopItem>>;
    getUPIConfig(): Promise<UPIConfig>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWebsiteConfig(): Promise<WebsiteConfig>;
    isCallerAdmin(): Promise<boolean>;
    registerWithMinecraftUsername(name: string, minecraftUsername: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateUPIConfig(upiId: string, merchantName: string): Promise<void>;
    updateUserMinecraftUsername(user: Principal, newMinecraftUsername: string): Promise<void>;
    updateWebsiteConfig(discordInviteLink: string, votePageUrls: Array<string>, serverIp: string, homeTagline: string, serverOnlineStatus: boolean, serverMemberCount: bigint, logo: Logo, backgroundSetting: BackgroundSetting): Promise<void>;
}
import type { BackgroundSetting as _BackgroundSetting, CartItem as _CartItem, ExternalBlob as _ExternalBlob, Logo as _Logo, OrderDetails as _OrderDetails, PurchaseRecord as _PurchaseRecord, PurchaseStatus as _PurchaseStatus, UserProfile as _UserProfile, UserRole as _UserRole, WebsiteConfig as _WebsiteConfig, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addShopItem(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addShopItem(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShopItem(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addToCart(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async approveOrder(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveOrder(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async completePurchaseWithUPI(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completePurchaseWithUPI(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completePurchaseWithUPI(arg0, arg1);
            return result;
        }
    }
    async deleteShopItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShopItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShopItem(arg0);
            return result;
        }
    }
    async editShopItem(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editShopItem(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editShopItem(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<OrderDetails>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllShopItems(): Promise<Array<ShopItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShopItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShopItems();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getPurchaseHistory(): Promise<Array<PurchaseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseHistory();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseHistory();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShopItemsByCategory(arg0: string): Promise<Array<ShopItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopItemsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopItemsByCategory(arg0);
            return result;
        }
    }
    async getUPIConfig(): Promise<UPIConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getUPIConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUPIConfig();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWebsiteConfig(): Promise<WebsiteConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebsiteConfig();
                return from_candid_WebsiteConfig_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebsiteConfig();
            return from_candid_WebsiteConfig_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerWithMinecraftUsername(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWithMinecraftUsername(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWithMinecraftUsername(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateUPIConfig(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUPIConfig(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUPIConfig(arg0, arg1);
            return result;
        }
    }
    async updateUserMinecraftUsername(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserMinecraftUsername(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserMinecraftUsername(arg0, arg1);
            return result;
        }
    }
    async updateWebsiteConfig(arg0: string, arg1: Array<string>, arg2: string, arg3: string, arg4: boolean, arg5: bigint, arg6: Logo, arg7: BackgroundSetting): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWebsiteConfig(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_Logo_n28(this._uploadFile, this._downloadFile, arg6), to_candid_BackgroundSetting_n31(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWebsiteConfig(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_Logo_n28(this._uploadFile, this._downloadFile, arg6), to_candid_BackgroundSetting_n31(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
}
function from_candid_BackgroundSetting_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BackgroundSetting): BackgroundSetting {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Logo_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Logo): Promise<Logo> {
    return await from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_OrderDetails_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderDetails): OrderDetails {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseRecord_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseRecord): PurchaseRecord {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseStatus): PurchaseStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_WebsiteConfig_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WebsiteConfig): Promise<WebsiteConfig> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PurchaseStatus;
    identityName: string;
    minecraftUsername: string;
    totalAmount: bigint;
    timestamp: bigint;
    purchaser: Principal;
    discordUsername: string;
    items: Array<_CartItem>;
}): {
    status: PurchaseStatus;
    identityName: string;
    minecraftUsername: string;
    totalAmount: bigint;
    timestamp: bigint;
    purchaser: Principal;
    discordUsername: string;
    items: Array<CartItem>;
} {
    return {
        status: from_candid_PurchaseStatus_n13(_uploadFile, _downloadFile, value.status),
        identityName: value.identityName,
        minecraftUsername: value.minecraftUsername,
        totalAmount: value.totalAmount,
        timestamp: value.timestamp,
        purchaser: value.purchaser,
        discordUsername: value.discordUsername,
        items: value.items
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PurchaseStatus;
    minecraftUsername: string;
    totalAmount: bigint;
    timestamp: bigint;
    discordUsername: string;
    items: Array<_CartItem>;
}): {
    status: PurchaseStatus;
    minecraftUsername: string;
    totalAmount: bigint;
    timestamp: bigint;
    discordUsername: string;
    items: Array<CartItem>;
} {
    return {
        status: from_candid_PurchaseStatus_n13(_uploadFile, _downloadFile, value.status),
        minecraftUsername: value.minecraftUsername,
        totalAmount: value.totalAmount,
        timestamp: value.timestamp,
        discordUsername: value.discordUsername,
        items: value.items
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    homeTagline: string;
    logo: _Logo;
    serverMemberCount: bigint;
    discordInviteLink: string;
    backgroundSetting: _BackgroundSetting;
    serverOnlineStatus: boolean;
    votePageUrls: Array<string>;
    serverIp: string;
}): Promise<{
    homeTagline: string;
    logo: Logo;
    serverMemberCount: bigint;
    discordInviteLink: string;
    backgroundSetting: BackgroundSetting;
    serverOnlineStatus: boolean;
    votePageUrls: Array<string>;
    serverIp: string;
}> {
    return {
        homeTagline: value.homeTagline,
        logo: await from_candid_Logo_n23(_uploadFile, _downloadFile, value.logo),
        serverMemberCount: value.serverMemberCount,
        discordInviteLink: value.discordInviteLink,
        backgroundSetting: from_candid_BackgroundSetting_n26(_uploadFile, _downloadFile, value.backgroundSetting),
        serverOnlineStatus: value.serverOnlineStatus,
        votePageUrls: value.votePageUrls,
        serverIp: value.serverIp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unapproved: null;
} | {
    approved: null;
}): PurchaseStatus {
    return "unapproved" in value ? PurchaseStatus.unapproved : "approved" in value ? PurchaseStatus.approved : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
} | {
    blob: _ExternalBlob;
}): Promise<{
    __kind__: "url";
    url: string;
} | {
    __kind__: "blob";
    blob: ExternalBlob;
}> {
    return "url" in value ? {
        __kind__: "url",
        url: value.url
    } : "blob" in value ? {
        __kind__: "blob",
        blob: await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.blob)
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color: {
        value: string;
    };
} | {
    image: {
        value: string;
    };
}): {
    __kind__: "color";
    color: {
        value: string;
    };
} | {
    __kind__: "image";
    image: {
        value: string;
    };
} {
    return "color" in value ? {
        __kind__: "color",
        color: value.color
    } : "image" in value ? {
        __kind__: "image",
        image: value.image
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderDetails>): Array<OrderDetails> {
    return value.map((x)=>from_candid_OrderDetails_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PurchaseRecord>): Array<PurchaseRecord> {
    return value.map((x)=>from_candid_PurchaseRecord_n19(_uploadFile, _downloadFile, x));
}
function to_candid_BackgroundSetting_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BackgroundSetting): _BackgroundSetting {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Logo_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Logo): Promise<_Logo> {
    return await to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "url";
    url: string;
} | {
    __kind__: "blob";
    blob: ExternalBlob;
}): Promise<{
    url: string;
} | {
    blob: _ExternalBlob;
}> {
    return value.__kind__ === "url" ? {
        url: value.url
    } : value.__kind__ === "blob" ? {
        blob: await to_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value.blob)
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "color";
    color: {
        value: string;
    };
} | {
    __kind__: "image";
    image: {
        value: string;
    };
}): {
    color: {
        value: string;
    };
} | {
    image: {
        value: string;
    };
} {
    return value.__kind__ === "color" ? {
        color: value.color
    } : value.__kind__ === "image" ? {
        image: value.image
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
